language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2

env:
  - DISPLAY=":99.0"
  - CODECLIMATE_REPO_TOKEN="8e91960e1ee121fdd4416283e64906591c21f2e28837857255e81f0913fc8fb1"

before_script:
  - 'sh -e /etc/init.d/xvfb start'

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"

gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2_beta.gemfile

matrix:
  fast_finish: true

notifications:
  email: false
